"""
Django settings for brav_core project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/
    
For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv  # <-- Add this import

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the root .env file
load_dotenv(BASE_DIR / ".env")  # <-- Add this line


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(b-azj+no=+z%megf7tqp@_lkbw^ruhe7_*g@!+10j%%89&tmt'
import os

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

        
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.sites",  # Required by allauth

    # Third-party apps
    'rest_framework',
    'corsheaders',
    'drf_spectacular',  # Add OpenAPI generator

    # Social Auth & Registration
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.facebook",
    "dj_rest_auth",
    "dj_rest_auth.registration",

    # security 
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    "rest_framework.authtoken",

    # apps

    'cart',
    'orders',
    'products',
    'reviews',
    'users',

]

SITE_ID = 1

# Tell allauth/dj-rest-auth to use your custom User model
AUTH_USER_MODEL = "users.User"
SOCIALACCOUNT_ADAPTER = "users.adapters.CustomSocialAccountAdapter"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

from datetime import timedelta

# --- SimpleJWT Settings ---
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),    # Short-lived Access Token
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),       # Refresh Token lifespan
    'ROTATE_REFRESH_TOKENS': True,                     # Issue a new refresh token upon refresh
    'BLACKLIST_AFTER_ROTATION': True,                  # Invalidate used refresh tokens
    'AUTH_HEADER_TYPES': ('Bearer',),
    
    # Cookie Specifics
    'AUTH_COOKIE': 'refresh_token',
    'AUTH_COOKIE_PATH': '/api/v1/users/token/refresh/',  # Scope cookie strictly to refresh endpoint
    'AUTH_COOKIE_HTTP_ONLY': True,                       # Prevents JS/XSS access
    'AUTH_COOKIE_SECURE': not os.getenv('DEBUG', 'True') == 'True', # True in Production (HTTPS)
    'AUTH_COOKIE_SAMESITE': 'Lax',                       # Prevents CSRF while preserving navigation
}

# --- CORS & CSRF Settings ---
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",        # Web Client Dev URL
    "http://127.0.0.1:3000",
    "https://yourdomain.com",       # Web Client Production URL
]

CORS_ALLOW_CREDENTIALS = True       # Mandatory: allows cookies to be sent with cross-origin requests

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://yourdomain.com",
]

CSRF_COOKIE_HTTP_ONLY = False       # Set to False so frontend JavaScript can read the CSRF token from cookie
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = not os.getenv('DEBUG', 'True') == 'True'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Place as high as possible

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    "allauth.account.middleware.AccountMiddleware",
]


# --- REST Framework & SimpleJWT Configuration ---
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
}

# CORS settings for frontend integration
CORS_ALLOW_ALL_ORIGINS = True

# Integrate SimpleJWT with dj-rest-auth
REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_HTTPONLY": False, # Handled via custom response/cookie helper
    "USER_DETAILS_SERIALIZER": "users.serializers.UserMeSerializer",
}

# --- Allauth Account & OAuth Settings ---
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_LOGIN_METHODS = {"email"}
# ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "none" # Set to "optional" or "mandatory" in production

SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_EMAIL_REQUIRED = True

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APPS": [
            {
                "client_id": os.getenv("GOOGLE_CLIENT_ID", ""),
                "secret": os.getenv("GOOGLE_CLIENT_SECRET", ""),
                "key": "",
            }
        ],
        "SCOPE": [
            "profile", 
            "email",
            "https://www.googleapis.com/auth/user.birthday.read", # Required for DOB
            "https://www.googleapis.com/auth/user.gender.read",   # Required for Gender
        ],
        "AUTH_PARAMS": {"access_type": "online"},
    },
    "facebook": {
        "APPS": [
            {
                "client_id": os.getenv("FACEBOOK_APP_ID", ""),
                "secret": os.getenv("FACEBOOK_APP_SECRET", ""),
                "key": "",
            }
        ],
        "METHOD": "oauth2",
        "SCOPE": ["email", "public_profile"],
        "FIELDS": ["id", "first_name", "last_name", "name", "picture"],
    },
}

FRONTEND_URL = os.getenv("FRONTEND_URL", "http://127.0.0.1:3000")

SPECTACULAR_SETTINGS = {
    'TITLE': 'Brav E-Commerce API',
    'DESCRIPTION': 'Modular Monolith E-Commerce Backend Service',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
}


ROOT_URLCONF = 'brav_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'brav_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
